version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - rabbitmq

  auth:
    build: ./auth
    expose:
      - "8000"

  rabbitmq:
    image: "rabbitmq:3-management" # использует образ RabbitMQ из Docker Hub
    ports:
      - "15672:15672" # Порт 15672 используется для веб-интерфейса управления RabbitMQ
      - "5672:5672" # Порт 5672 используется для стандартного AMQP-протокола
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
#    environment:
#      - DATABASE_URL=postgres://user:password@db:5432/auth_service

#  db:
#    image: postgres:13
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password

#volumes:
#  postgres_data:
